name: Canary Release
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type (canary or release)"
        required: true
        type: choice
        options:
          - canary
          - release
      semanticVersionType:
        description: "Semantic version type (major, minor, or patch)"
        required: false
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run script
        run: node ./scripts.startRelease.js ${{ github.event.inputs.releaseType }} ${{ github.event.inputs.semanticVersionType }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
